[server]
# Streamlit Cloud runs on port 8501 by default
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#FFDE4D"
backgroundColor = "#FAF6EE"
secondaryBackgroundColor = "#F3EDE0"
textColor = "#000000"
font = "monospace"
